#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 143
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 73
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_PIPE = 1,
  anon_sym_AMP = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_QMARK = 5,
  anon_sym_STAR = 6,
  anon_sym_ATconstraint = 7,
  anon_sym_ATsource = 8,
  anon_sym_LBRACK = 9,
  anon_sym_COMMA = 10,
  anon_sym_RBRACK = 11,
  anon_sym_for = 12,
  anon_sym_AT = 13,
  anon_sym__ = 14,
  anon_sym_0 = 15,
  anon_sym_1 = 16,
  anon_sym_Concrete = 17,
  anon_sym_LT = 18,
  anon_sym_GT = 19,
  anon_sym_LPAREN = 20,
  anon_sym_RPAREN = 21,
  anon_sym_AMP_AMP = 22,
  anon_sym_PIPE_PIPE = 23,
  anon_sym_EQ_EQ = 24,
  anon_sym_BANG_EQ = 25,
  anon_sym_GT_EQ = 26,
  anon_sym_LT_EQ = 27,
  anon_sym_BANG = 28,
  anon_sym_DOT = 29,
  anon_sym_EQ_GT = 30,
  sym_type_ident = 31,
  sym_ident = 32,
  sym_number = 33,
  aux_sym_comment_token1 = 34,
  aux_sym_comment_token2 = 35,
  sym_source_file = 36,
  sym__top_level = 37,
  sym_type_def = 38,
  sym__type_body = 39,
  sym__type_expr = 40,
  sym_block = 41,
  sym_name = 42,
  sym__block_item = 43,
  sym_field = 44,
  sym__field_value = 45,
  sym_nested_block = 46,
  sym_constraint = 47,
  sym_source = 48,
  sym_annotation = 49,
  sym_wildcard = 50,
  sym_wildcard_object = 51,
  sym_concrete_type = 52,
  sym_list_type = 53,
  sym_inline_object = 54,
  sym_type_args = 55,
  sym_expr = 56,
  sym_call_expr = 57,
  sym_binary_expr = 58,
  sym_unary_expr = 59,
  sym_member_expr = 60,
  sym_lambda_expr = 61,
  sym_expr_list = 62,
  sym_comment = 63,
  aux_sym_source_file_repeat1 = 64,
  aux_sym_type_def_repeat1 = 65,
  aux_sym_type_def_repeat2 = 66,
  aux_sym_block_repeat1 = 67,
  aux_sym_source_repeat1 = 68,
  aux_sym_annotation_repeat1 = 69,
  aux_sym_inline_object_repeat1 = 70,
  aux_sym_type_args_repeat1 = 71,
  aux_sym_expr_list_repeat1 = 72,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PIPE] = "|",
  [anon_sym_AMP] = "&",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_QMARK] = "\?",
  [anon_sym_STAR] = "*",
  [anon_sym_ATconstraint] = "@constraint",
  [anon_sym_ATsource] = "@source",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_for] = "for",
  [anon_sym_AT] = "@",
  [anon_sym__] = "_",
  [anon_sym_0] = "0",
  [anon_sym_1] = "1",
  [anon_sym_Concrete] = "Concrete",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_BANG] = "!",
  [anon_sym_DOT] = ".",
  [anon_sym_EQ_GT] = "=>",
  [sym_type_ident] = "type_ident",
  [sym_ident] = "ident",
  [sym_number] = "number",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [sym_source_file] = "source_file",
  [sym__top_level] = "_top_level",
  [sym_type_def] = "type_def",
  [sym__type_body] = "_type_body",
  [sym__type_expr] = "_type_expr",
  [sym_block] = "block",
  [sym_name] = "name",
  [sym__block_item] = "_block_item",
  [sym_field] = "field",
  [sym__field_value] = "_field_value",
  [sym_nested_block] = "nested_block",
  [sym_constraint] = "constraint",
  [sym_source] = "source",
  [sym_annotation] = "annotation",
  [sym_wildcard] = "wildcard",
  [sym_wildcard_object] = "wildcard_object",
  [sym_concrete_type] = "concrete_type",
  [sym_list_type] = "list_type",
  [sym_inline_object] = "inline_object",
  [sym_type_args] = "type_args",
  [sym_expr] = "expr",
  [sym_call_expr] = "call_expr",
  [sym_binary_expr] = "binary_expr",
  [sym_unary_expr] = "unary_expr",
  [sym_member_expr] = "member_expr",
  [sym_lambda_expr] = "lambda_expr",
  [sym_expr_list] = "expr_list",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_type_def_repeat1] = "type_def_repeat1",
  [aux_sym_type_def_repeat2] = "type_def_repeat2",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_annotation_repeat1] = "annotation_repeat1",
  [aux_sym_inline_object_repeat1] = "inline_object_repeat1",
  [aux_sym_type_args_repeat1] = "type_args_repeat1",
  [aux_sym_expr_list_repeat1] = "expr_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_ATconstraint] = anon_sym_ATconstraint,
  [anon_sym_ATsource] = anon_sym_ATsource,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym__] = anon_sym__,
  [anon_sym_0] = anon_sym_0,
  [anon_sym_1] = anon_sym_1,
  [anon_sym_Concrete] = anon_sym_Concrete,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [sym_type_ident] = sym_type_ident,
  [sym_ident] = sym_ident,
  [sym_number] = sym_number,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [sym_source_file] = sym_source_file,
  [sym__top_level] = sym__top_level,
  [sym_type_def] = sym_type_def,
  [sym__type_body] = sym__type_body,
  [sym__type_expr] = sym__type_expr,
  [sym_block] = sym_block,
  [sym_name] = sym_name,
  [sym__block_item] = sym__block_item,
  [sym_field] = sym_field,
  [sym__field_value] = sym__field_value,
  [sym_nested_block] = sym_nested_block,
  [sym_constraint] = sym_constraint,
  [sym_source] = sym_source,
  [sym_annotation] = sym_annotation,
  [sym_wildcard] = sym_wildcard,
  [sym_wildcard_object] = sym_wildcard_object,
  [sym_concrete_type] = sym_concrete_type,
  [sym_list_type] = sym_list_type,
  [sym_inline_object] = sym_inline_object,
  [sym_type_args] = sym_type_args,
  [sym_expr] = sym_expr,
  [sym_call_expr] = sym_call_expr,
  [sym_binary_expr] = sym_binary_expr,
  [sym_unary_expr] = sym_unary_expr,
  [sym_member_expr] = sym_member_expr,
  [sym_lambda_expr] = sym_lambda_expr,
  [sym_expr_list] = sym_expr_list,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_type_def_repeat1] = aux_sym_type_def_repeat1,
  [aux_sym_type_def_repeat2] = aux_sym_type_def_repeat2,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_annotation_repeat1] = aux_sym_annotation_repeat1,
  [aux_sym_inline_object_repeat1] = aux_sym_inline_object_repeat1,
  [aux_sym_type_args_repeat1] = aux_sym_type_args_repeat1,
  [aux_sym_expr_list_repeat1] = aux_sym_expr_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATconstraint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATsource] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Concrete] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_type_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level] = {
    .visible = false,
    .named = true,
  },
  [sym_type_def] = {
    .visible = true,
    .named = true,
  },
  [sym__type_body] = {
    .visible = false,
    .named = true,
  },
  [sym__type_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym__block_item] = {
    .visible = false,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym__field_value] = {
    .visible = false,
    .named = true,
  },
  [sym_nested_block] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_wildcard] = {
    .visible = true,
    .named = true,
  },
  [sym_wildcard_object] = {
    .visible = true,
    .named = true,
  },
  [sym_concrete_type] = {
    .visible = true,
    .named = true,
  },
  [sym_list_type] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_object] = {
    .visible = true,
    .named = true,
  },
  [sym_type_args] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_member_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_expr_list] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_def_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_def_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_annotation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_inline_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expr_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 68,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 78,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 118,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 115,
  [140] = 126,
  [141] = 141,
  [142] = 142,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      if (lookahead == '!') ADVANCE(57);
      if (lookahead == '&') ADVANCE(28);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == ')') ADVANCE(49);
      if (lookahead == '*') ADVANCE(32);
      if (lookahead == ',') ADVANCE(36);
      if (lookahead == '.') ADVANCE(58);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '0') ADVANCE(42);
      if (lookahead == '1') ADVANCE(43);
      if (lookahead == '<') ADVANCE(46);
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == '>') ADVANCE(47);
      if (lookahead == '?') ADVANCE(31);
      if (lookahead == '@') ADVANCE(40);
      if (lookahead == 'C') ADVANCE(64);
      if (lookahead == '[') ADVANCE(35);
      if (lookahead == ']') ADVANCE(37);
      if (lookahead == '_') ADVANCE(41);
      if (lookahead == 'f') ADVANCE(68);
      if (lookahead == '{') ADVANCE(29);
      if (lookahead == '|') ADVANCE(26);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('2' <= lookahead && lookahead <= '9')) ADVANCE(71);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(67);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '&') ADVANCE(2);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == ')') ADVANCE(49);
      if (lookahead == '*') ADVANCE(32);
      if (lookahead == ',') ADVANCE(36);
      if (lookahead == '.') ADVANCE(58);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '0') ADVANCE(42);
      if (lookahead == '1') ADVANCE(43);
      if (lookahead == '<') ADVANCE(46);
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == '>') ADVANCE(47);
      if (lookahead == '@') ADVANCE(40);
      if (lookahead == '|') ADVANCE(22);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('2' <= lookahead && lookahead <= '9')) ADVANCE(71);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 2:
      if (lookahead == '&') ADVANCE(50);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(72);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(73);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(53);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(52);
      if (lookahead == '>') ADVANCE(59);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 22:
      if (lookahead == '|') ADVANCE(51);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      if (lookahead == '!') ADVANCE(56);
      if (lookahead == '&') ADVANCE(27);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == ')') ADVANCE(49);
      if (lookahead == '*') ADVANCE(32);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '0') ADVANCE(42);
      if (lookahead == '1') ADVANCE(43);
      if (lookahead == '<') ADVANCE(45);
      if (lookahead == '?') ADVANCE(31);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '[') ADVANCE(35);
      if (lookahead == '_') ADVANCE(41);
      if (lookahead == '{') ADVANCE(29);
      if (lookahead == '|') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(23)
      if (('2' <= lookahead && lookahead <= '9')) ADVANCE(71);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(67);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(51);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '&') ADVANCE(50);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_ATconstraint);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_ATsource);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_for);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == 'c') ADVANCE(14);
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_Concrete);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(55);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(54);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(53);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_type_ident);
      if (lookahead == 'c') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_type_ident);
      if (lookahead == 'e') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_type_ident);
      if (lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_type_ident);
      if (lookahead == 'n') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_type_ident);
      if (lookahead == 'o') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_type_ident);
      if (lookahead == 'r') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_type_ident);
      if (lookahead == 't') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_type_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'o') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 23},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 23},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 23},
  [22] = {.lex_state = 23},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 23},
  [25] = {.lex_state = 23},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 23},
  [28] = {.lex_state = 23},
  [29] = {.lex_state = 23},
  [30] = {.lex_state = 23},
  [31] = {.lex_state = 23},
  [32] = {.lex_state = 23},
  [33] = {.lex_state = 23},
  [34] = {.lex_state = 23},
  [35] = {.lex_state = 23},
  [36] = {.lex_state = 23},
  [37] = {.lex_state = 23},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 23},
  [40] = {.lex_state = 23},
  [41] = {.lex_state = 23},
  [42] = {.lex_state = 23},
  [43] = {.lex_state = 23},
  [44] = {.lex_state = 23},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 23},
  [47] = {.lex_state = 23},
  [48] = {.lex_state = 23},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 23},
  [53] = {.lex_state = 23},
  [54] = {.lex_state = 23},
  [55] = {.lex_state = 23},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 23},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 23},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 23},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 23},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 23},
  [69] = {.lex_state = 23},
  [70] = {.lex_state = 23},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 23},
  [76] = {.lex_state = 23},
  [77] = {.lex_state = 23},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 23},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 23},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 23},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 23},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 23},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 23},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 23},
  [101] = {.lex_state = 23},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 23},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 23},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 23},
  [114] = {.lex_state = 23},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 23},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 23},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 23},
  [127] = {.lex_state = 23},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 23},
  [130] = {.lex_state = 23},
  [131] = {.lex_state = 23},
  [132] = {.lex_state = 23},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 23},
  [135] = {.lex_state = 23},
  [136] = {.lex_state = 23},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 23},
  [141] = {.lex_state = 23},
  [142] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_ATconstraint] = ACTIONS(1),
    [anon_sym_ATsource] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [anon_sym_1] = ACTIONS(1),
    [anon_sym_Concrete] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [sym_type_ident] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(3),
    [aux_sym_comment_token2] = ACTIONS(5),
  },
  [1] = {
    [sym_source_file] = STATE(138),
    [sym__top_level] = STATE(82),
    [sym_type_def] = STATE(84),
    [sym_block] = STATE(84),
    [sym_annotation] = STATE(92),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(34),
    [aux_sym_type_def_repeat1] = STATE(76),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_AT] = ACTIONS(5),
    [sym_type_ident] = ACTIONS(9),
    [aux_sym_comment_token1] = ACTIONS(3),
    [aux_sym_comment_token2] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_EQ_GT,
    STATE(2), 1,
      sym_comment,
    ACTIONS(13), 3,
      anon_sym_AT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(11), 13,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_DOT,
      sym_ident,
  [36] = 15,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      anon_sym_STAR,
    ACTIONS(23), 1,
      anon_sym_ATconstraint,
    ACTIONS(25), 1,
      anon_sym_ATsource,
    ACTIONS(27), 1,
      anon_sym_AT,
    ACTIONS(31), 1,
      sym_ident,
    STATE(3), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym_block_repeat1,
    STATE(65), 1,
      sym__block_item,
    STATE(75), 1,
      aux_sym_type_def_repeat1,
    STATE(92), 1,
      sym_annotation,
    ACTIONS(29), 3,
      anon_sym_0,
      anon_sym_1,
      sym_number,
    STATE(66), 4,
      sym_field,
      sym_nested_block,
      sym_constraint,
      sym_source,
  [87] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(4), 1,
      sym_comment,
    ACTIONS(35), 3,
      anon_sym_AT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 13,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_DOT,
      sym_ident,
  [120] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(5), 1,
      sym_comment,
    ACTIONS(41), 3,
      anon_sym_AT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(39), 13,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_DOT,
      sym_ident,
  [150] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(45), 1,
      anon_sym_AT,
    ACTIONS(51), 1,
      anon_sym_DOT,
    STATE(6), 1,
      sym_comment,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(43), 6,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_ident,
    ACTIONS(49), 6,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [186] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(7), 1,
      sym_comment,
    ACTIONS(55), 3,
      anon_sym_AT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 13,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_DOT,
      sym_ident,
  [216] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(51), 1,
      anon_sym_DOT,
    STATE(8), 1,
      sym_comment,
    ACTIONS(59), 3,
      anon_sym_AT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(57), 12,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym_ident,
  [248] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(9), 1,
      sym_comment,
    ACTIONS(63), 3,
      anon_sym_AT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(61), 13,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_DOT,
      sym_ident,
  [278] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(10), 1,
      sym_comment,
    ACTIONS(13), 3,
      anon_sym_AT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(11), 13,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_DOT,
      sym_ident,
  [308] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(51), 1,
      anon_sym_DOT,
    STATE(11), 1,
      sym_comment,
    ACTIONS(67), 3,
      anon_sym_AT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(65), 12,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym_ident,
  [340] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(12), 1,
      sym_comment,
    ACTIONS(71), 3,
      anon_sym_AT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(69), 13,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_DOT,
      sym_ident,
  [370] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(13), 1,
      sym_comment,
    ACTIONS(75), 3,
      anon_sym_AT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(73), 13,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_DOT,
      sym_ident,
  [400] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(51), 1,
      anon_sym_DOT,
    ACTIONS(79), 1,
      anon_sym_AT,
    STATE(14), 1,
      sym_comment,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 4,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      sym_ident,
    ACTIONS(49), 6,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [434] = 13,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(23), 1,
      anon_sym_ATconstraint,
    ACTIONS(25), 1,
      anon_sym_ATsource,
    ACTIONS(27), 1,
      anon_sym_AT,
    ACTIONS(31), 1,
      sym_ident,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      sym_comment,
    STATE(16), 1,
      aux_sym_block_repeat1,
    STATE(65), 1,
      sym__block_item,
    STATE(75), 1,
      aux_sym_type_def_repeat1,
    STATE(92), 1,
      sym_annotation,
    STATE(66), 4,
      sym_field,
      sym_nested_block,
      sym_constraint,
      sym_source,
  [477] = 12,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    ACTIONS(85), 1,
      anon_sym_ATconstraint,
    ACTIONS(88), 1,
      anon_sym_ATsource,
    ACTIONS(91), 1,
      anon_sym_AT,
    ACTIONS(94), 1,
      sym_ident,
    STATE(65), 1,
      sym__block_item,
    STATE(75), 1,
      aux_sym_type_def_repeat1,
    STATE(92), 1,
      sym_annotation,
    STATE(16), 2,
      sym_comment,
      aux_sym_block_repeat1,
    STATE(66), 4,
      sym_field,
      sym_nested_block,
      sym_constraint,
      sym_source,
  [518] = 12,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(101), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      anon_sym_LT,
    ACTIONS(105), 1,
      sym_ident,
    STATE(17), 1,
      sym_comment,
    STATE(46), 1,
      sym__type_body,
    STATE(47), 1,
      aux_sym_type_def_repeat2,
    STATE(123), 1,
      sym_name,
    ACTIONS(99), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    STATE(62), 2,
      sym_wildcard_object,
      sym_type_args,
    ACTIONS(97), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_type_ident,
  [559] = 13,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(23), 1,
      anon_sym_ATconstraint,
    ACTIONS(25), 1,
      anon_sym_ATsource,
    ACTIONS(27), 1,
      anon_sym_AT,
    ACTIONS(31), 1,
      sym_ident,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_block_repeat1,
    STATE(18), 1,
      sym_comment,
    STATE(65), 1,
      sym__block_item,
    STATE(75), 1,
      aux_sym_type_def_repeat1,
    STATE(92), 1,
      sym_annotation,
    STATE(66), 4,
      sym_field,
      sym_nested_block,
      sym_constraint,
      sym_source,
  [602] = 13,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(23), 1,
      anon_sym_ATconstraint,
    ACTIONS(25), 1,
      anon_sym_ATsource,
    ACTIONS(27), 1,
      anon_sym_AT,
    ACTIONS(31), 1,
      sym_ident,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    STATE(18), 1,
      aux_sym_block_repeat1,
    STATE(19), 1,
      sym_comment,
    STATE(65), 1,
      sym__block_item,
    STATE(75), 1,
      aux_sym_type_def_repeat1,
    STATE(92), 1,
      sym_annotation,
    STATE(66), 4,
      sym_field,
      sym_nested_block,
      sym_constraint,
      sym_source,
  [645] = 9,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(51), 1,
      anon_sym_DOT,
    ACTIONS(109), 1,
      anon_sym_COMMA,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    STATE(20), 1,
      sym_comment,
    STATE(102), 1,
      aux_sym_expr_list_repeat1,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 6,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [679] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    ACTIONS(117), 1,
      anon_sym_BANG,
    ACTIONS(119), 1,
      sym_ident,
    STATE(20), 1,
      sym_expr,
    STATE(21), 1,
      sym_comment,
    STATE(112), 1,
      sym_expr_list,
    STATE(10), 5,
      sym_call_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_member_expr,
      sym_lambda_expr,
  [714] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(103), 1,
      anon_sym_LT,
    ACTIONS(123), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym_comment,
    STATE(40), 1,
      aux_sym_type_def_repeat2,
    STATE(43), 1,
      sym__type_body,
    ACTIONS(99), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    STATE(62), 2,
      sym_wildcard_object,
      sym_type_args,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_type_ident,
  [749] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(51), 1,
      anon_sym_DOT,
    STATE(23), 1,
      sym_comment,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(125), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(49), 6,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [778] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      anon_sym_BANG,
    ACTIONS(119), 1,
      sym_ident,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    STATE(20), 1,
      sym_expr,
    STATE(24), 1,
      sym_comment,
    STATE(133), 1,
      sym_expr_list,
    STATE(10), 5,
      sym_call_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_member_expr,
      sym_lambda_expr,
  [813] = 12,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_QMARK,
    ACTIONS(133), 1,
      anon_sym_STAR,
    ACTIONS(135), 1,
      anon_sym_LBRACK,
    ACTIONS(137), 1,
      anon_sym__,
    ACTIONS(139), 1,
      sym_type_ident,
    STATE(25), 1,
      sym_comment,
    STATE(50), 1,
      sym__field_value,
    STATE(59), 1,
      sym_wildcard_object,
    STATE(57), 2,
      sym_wildcard,
      sym_list_type,
  [851] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(51), 1,
      anon_sym_DOT,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    STATE(26), 1,
      sym_comment,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 6,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [879] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
    ACTIONS(145), 1,
      anon_sym_AT,
    ACTIONS(148), 1,
      sym_type_ident,
    STATE(76), 1,
      aux_sym_type_def_repeat1,
    STATE(82), 1,
      sym__top_level,
    STATE(92), 1,
      sym_annotation,
    STATE(27), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(84), 2,
      sym_type_def,
      sym_block,
  [912] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      anon_sym_BANG,
    ACTIONS(119), 1,
      sym_ident,
    STATE(11), 1,
      sym_expr,
    STATE(28), 1,
      sym_comment,
    STATE(10), 5,
      sym_call_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_member_expr,
      sym_lambda_expr,
  [941] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      anon_sym_BANG,
    ACTIONS(119), 1,
      sym_ident,
    STATE(23), 1,
      sym_expr,
    STATE(29), 1,
      sym_comment,
    STATE(10), 5,
      sym_call_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_member_expr,
      sym_lambda_expr,
  [970] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      anon_sym_BANG,
    ACTIONS(119), 1,
      sym_ident,
    STATE(14), 1,
      sym_expr,
    STATE(30), 1,
      sym_comment,
    STATE(10), 5,
      sym_call_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_member_expr,
      sym_lambda_expr,
  [999] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      anon_sym_BANG,
    ACTIONS(119), 1,
      sym_ident,
    STATE(26), 1,
      sym_expr,
    STATE(31), 1,
      sym_comment,
    STATE(10), 5,
      sym_call_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_member_expr,
      sym_lambda_expr,
  [1028] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      anon_sym_BANG,
    ACTIONS(119), 1,
      sym_ident,
    STATE(8), 1,
      sym_expr,
    STATE(32), 1,
      sym_comment,
    STATE(10), 5,
      sym_call_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_member_expr,
      sym_lambda_expr,
  [1057] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      anon_sym_BANG,
    ACTIONS(119), 1,
      sym_ident,
    STATE(6), 1,
      sym_expr,
    STATE(33), 1,
      sym_comment,
    STATE(10), 5,
      sym_call_expr,
      sym_binary_expr,
      sym_unary_expr,
      sym_member_expr,
      sym_lambda_expr,
  [1086] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      sym_type_ident,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    STATE(27), 1,
      aux_sym_source_file_repeat1,
    STATE(34), 1,
      sym_comment,
    STATE(76), 1,
      aux_sym_type_def_repeat1,
    STATE(82), 1,
      sym__top_level,
    STATE(92), 1,
      sym_annotation,
    ACTIONS(5), 2,
      anon_sym_AT,
      aux_sym_comment_token2,
    STATE(84), 2,
      sym_type_def,
      sym_block,
  [1119] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(135), 1,
      anon_sym_LBRACK,
    ACTIONS(137), 1,
      anon_sym__,
    ACTIONS(139), 1,
      sym_type_ident,
    ACTIONS(153), 1,
      anon_sym_QMARK,
    ACTIONS(155), 1,
      anon_sym_STAR,
    STATE(35), 1,
      sym_comment,
    STATE(61), 1,
      sym__field_value,
    STATE(57), 2,
      sym_wildcard,
      sym_list_type,
  [1151] = 9,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(135), 1,
      anon_sym_LBRACK,
    ACTIONS(137), 1,
      anon_sym__,
    ACTIONS(139), 1,
      sym_type_ident,
    ACTIONS(155), 1,
      anon_sym_STAR,
    STATE(36), 1,
      sym_comment,
    STATE(61), 1,
      sym__field_value,
    STATE(57), 2,
      sym_wildcard,
      sym_list_type,
  [1180] = 9,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(135), 1,
      anon_sym_LBRACK,
    ACTIONS(137), 1,
      anon_sym__,
    ACTIONS(139), 1,
      sym_type_ident,
    ACTIONS(157), 1,
      anon_sym_STAR,
    STATE(37), 1,
      sym_comment,
    STATE(67), 1,
      sym__field_value,
    STATE(57), 2,
      sym_wildcard,
      sym_list_type,
  [1209] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 1,
      anon_sym_Concrete,
    ACTIONS(163), 1,
      sym_type_ident,
    STATE(38), 1,
      sym_comment,
    STATE(52), 1,
      sym__type_expr,
    STATE(53), 3,
      sym_wildcard_object,
      sym_concrete_type,
      sym_inline_object,
  [1236] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(135), 1,
      anon_sym_LBRACK,
    ACTIONS(137), 1,
      anon_sym__,
    ACTIONS(139), 1,
      sym_type_ident,
    STATE(39), 1,
      sym_comment,
    STATE(51), 1,
      sym__field_value,
    STATE(57), 2,
      sym_wildcard,
      sym_list_type,
  [1262] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(40), 1,
      sym_comment,
    STATE(41), 1,
      aux_sym_type_def_repeat2,
    ACTIONS(99), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(165), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_type_ident,
  [1284] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(169), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    STATE(41), 2,
      sym_comment,
      aux_sym_type_def_repeat2,
    ACTIONS(167), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_type_ident,
  [1304] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(135), 1,
      anon_sym_LBRACK,
    ACTIONS(137), 1,
      anon_sym__,
    ACTIONS(139), 1,
      sym_type_ident,
    STATE(42), 1,
      sym_comment,
    STATE(67), 1,
      sym__field_value,
    STATE(57), 2,
      sym_wildcard,
      sym_list_type,
  [1330] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(43), 1,
      sym_comment,
    STATE(44), 1,
      aux_sym_type_def_repeat2,
    ACTIONS(99), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(165), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_type_ident,
  [1352] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(41), 1,
      aux_sym_type_def_repeat2,
    STATE(44), 1,
      sym_comment,
    ACTIONS(99), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(172), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_type_ident,
  [1374] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(176), 1,
      anon_sym_for,
    STATE(45), 1,
      sym_comment,
    ACTIONS(178), 2,
      anon_sym_AT,
      sym_ident,
    ACTIONS(174), 3,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
  [1396] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(40), 1,
      aux_sym_type_def_repeat2,
    STATE(46), 1,
      sym_comment,
    ACTIONS(99), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_type_ident,
  [1418] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(41), 1,
      aux_sym_type_def_repeat2,
    STATE(47), 1,
      sym_comment,
    ACTIONS(99), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_type_ident,
  [1440] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(135), 1,
      anon_sym_LBRACK,
    ACTIONS(137), 1,
      anon_sym__,
    ACTIONS(139), 1,
      sym_type_ident,
    STATE(48), 1,
      sym_comment,
    STATE(61), 1,
      sym__field_value,
    STATE(57), 2,
      sym_wildcard,
      sym_list_type,
  [1466] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(182), 1,
      anon_sym_for,
    STATE(49), 1,
      sym_comment,
    ACTIONS(184), 2,
      anon_sym_AT,
      sym_ident,
    ACTIONS(180), 3,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
  [1488] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(188), 1,
      anon_sym_AT,
    STATE(50), 1,
      sym_comment,
    ACTIONS(186), 4,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      sym_ident,
  [1507] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(192), 1,
      anon_sym_AT,
    STATE(51), 1,
      sym_comment,
    ACTIONS(190), 4,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      sym_ident,
  [1526] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(52), 1,
      sym_comment,
    ACTIONS(167), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_AT,
      sym_type_ident,
  [1543] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(53), 1,
      sym_comment,
    ACTIONS(194), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_AT,
      sym_type_ident,
  [1560] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(21), 1,
      anon_sym_STAR,
    ACTIONS(196), 1,
      sym_ident,
    STATE(54), 1,
      sym_comment,
    ACTIONS(29), 3,
      anon_sym_0,
      anon_sym_1,
      sym_number,
  [1581] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(198), 1,
      anon_sym_AT,
    STATE(92), 1,
      sym_annotation,
    ACTIONS(201), 2,
      sym_type_ident,
      sym_ident,
    STATE(55), 2,
      sym_comment,
      aux_sym_type_def_repeat1,
  [1602] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(205), 1,
      anon_sym_AT,
    STATE(56), 1,
      sym_comment,
    ACTIONS(203), 4,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      sym_ident,
  [1621] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(209), 1,
      anon_sym_AT,
    STATE(57), 1,
      sym_comment,
    ACTIONS(207), 4,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      sym_ident,
  [1640] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(58), 1,
      sym_comment,
    ACTIONS(211), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_AT,
      sym_type_ident,
  [1657] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(215), 1,
      anon_sym_AT,
    STATE(59), 1,
      sym_comment,
    ACTIONS(213), 4,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      sym_ident,
  [1676] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(60), 1,
      sym_comment,
    ACTIONS(217), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_AT,
      sym_type_ident,
  [1693] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(221), 1,
      anon_sym_AT,
    STATE(61), 1,
      sym_comment,
    ACTIONS(219), 4,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      sym_ident,
  [1712] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(62), 1,
      sym_comment,
    ACTIONS(223), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_AT,
      sym_type_ident,
  [1729] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(227), 1,
      anon_sym_AT,
    STATE(63), 1,
      sym_comment,
    ACTIONS(225), 4,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      sym_ident,
  [1748] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(64), 1,
      sym_comment,
    ACTIONS(229), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_AT,
      sym_type_ident,
  [1765] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(233), 1,
      anon_sym_AT,
    STATE(65), 1,
      sym_comment,
    ACTIONS(231), 4,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      sym_ident,
  [1784] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(237), 1,
      anon_sym_AT,
    STATE(66), 1,
      sym_comment,
    ACTIONS(235), 4,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      sym_ident,
  [1803] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(241), 1,
      anon_sym_AT,
    STATE(67), 1,
      sym_comment,
    ACTIONS(239), 4,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      sym_ident,
  [1822] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(68), 1,
      sym_comment,
    ACTIONS(243), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_AT,
      sym_type_ident,
  [1839] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(69), 1,
      sym_comment,
    ACTIONS(245), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_AT,
      sym_type_ident,
  [1856] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(70), 1,
      sym_comment,
    ACTIONS(247), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_AT,
      sym_type_ident,
  [1873] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(251), 1,
      anon_sym_AT,
    STATE(71), 1,
      sym_comment,
    ACTIONS(249), 4,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      sym_ident,
  [1892] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(255), 1,
      anon_sym_AT,
    STATE(72), 1,
      sym_comment,
    ACTIONS(253), 4,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      sym_ident,
  [1911] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(259), 1,
      anon_sym_AT,
    STATE(73), 1,
      sym_comment,
    ACTIONS(257), 4,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      sym_ident,
  [1930] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(261), 1,
      anon_sym_AT,
    STATE(74), 1,
      sym_comment,
    ACTIONS(243), 4,
      anon_sym_RBRACE,
      anon_sym_ATconstraint,
      anon_sym_ATsource,
      sym_ident,
  [1949] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(263), 1,
      sym_ident,
    STATE(55), 1,
      aux_sym_type_def_repeat1,
    STATE(75), 1,
      sym_comment,
    STATE(92), 1,
      sym_annotation,
    ACTIONS(5), 2,
      anon_sym_AT,
      aux_sym_comment_token2,
  [1969] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(265), 1,
      sym_type_ident,
    STATE(55), 1,
      aux_sym_type_def_repeat1,
    STATE(76), 1,
      sym_comment,
    STATE(92), 1,
      sym_annotation,
    ACTIONS(5), 2,
      anon_sym_AT,
      aux_sym_comment_token2,
  [1989] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(267), 1,
      anon_sym_LBRACK,
    STATE(77), 1,
      sym_comment,
    ACTIONS(269), 3,
      anon_sym_AT,
      sym_type_ident,
      sym_ident,
  [2007] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(271), 1,
      anon_sym_STAR,
    STATE(78), 1,
      sym_comment,
    ACTIONS(273), 3,
      anon_sym_0,
      anon_sym_1,
      sym_number,
  [2025] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(21), 1,
      anon_sym_STAR,
    STATE(79), 1,
      sym_comment,
    ACTIONS(29), 3,
      anon_sym_0,
      anon_sym_1,
      sym_number,
  [2043] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    ACTIONS(277), 1,
      anon_sym_RBRACK,
    STATE(80), 1,
      sym_comment,
    STATE(91), 1,
      aux_sym_annotation_repeat1,
  [2062] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(279), 1,
      anon_sym_RBRACE,
    ACTIONS(281), 1,
      anon_sym_COMMA,
    STATE(81), 2,
      sym_comment,
      aux_sym_inline_object_repeat1,
  [2079] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(82), 1,
      sym_comment,
    ACTIONS(284), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_type_ident,
  [2094] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(288), 1,
      anon_sym_RBRACK,
    STATE(83), 1,
      sym_comment,
    STATE(99), 1,
      aux_sym_source_repeat1,
  [2113] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(84), 1,
      sym_comment,
    ACTIONS(290), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_type_ident,
  [2128] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(292), 1,
      anon_sym_RBRACK,
    STATE(83), 1,
      aux_sym_source_repeat1,
    STATE(85), 1,
      sym_comment,
  [2147] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(294), 1,
      anon_sym_RBRACK,
    STATE(86), 1,
      sym_comment,
    STATE(105), 1,
      aux_sym_source_repeat1,
  [2166] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(296), 1,
      anon_sym_COMMA,
    ACTIONS(299), 1,
      anon_sym_GT,
    STATE(87), 2,
      sym_comment,
      aux_sym_type_args_repeat1,
  [2183] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(88), 1,
      sym_comment,
    ACTIONS(301), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_type_ident,
  [2198] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(292), 1,
      anon_sym_RBRACK,
    STATE(89), 1,
      sym_comment,
    STATE(99), 1,
      aux_sym_source_repeat1,
  [2217] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(90), 1,
      sym_comment,
    ACTIONS(303), 3,
      anon_sym_AT,
      sym_type_ident,
      sym_ident,
  [2232] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(305), 1,
      anon_sym_COMMA,
    ACTIONS(308), 1,
      anon_sym_RBRACK,
    STATE(91), 2,
      sym_comment,
      aux_sym_annotation_repeat1,
  [2249] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(92), 1,
      sym_comment,
    ACTIONS(310), 3,
      anon_sym_AT,
      sym_type_ident,
      sym_ident,
  [2264] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(312), 1,
      anon_sym_RBRACK,
    STATE(89), 1,
      aux_sym_source_repeat1,
    STATE(93), 1,
      sym_comment,
  [2283] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(314), 1,
      anon_sym_RBRACE,
    ACTIONS(316), 1,
      anon_sym_COMMA,
    STATE(81), 1,
      aux_sym_inline_object_repeat1,
    STATE(94), 1,
      sym_comment,
  [2302] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(316), 1,
      anon_sym_COMMA,
    ACTIONS(318), 1,
      anon_sym_RBRACE,
    STATE(94), 1,
      aux_sym_inline_object_repeat1,
    STATE(95), 1,
      sym_comment,
  [2321] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(96), 1,
      sym_comment,
    ACTIONS(320), 3,
      anon_sym_AT,
      sym_type_ident,
      sym_ident,
  [2336] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    ACTIONS(322), 1,
      anon_sym_COMMA,
    STATE(97), 2,
      sym_comment,
      aux_sym_expr_list_repeat1,
  [2353] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(325), 1,
      anon_sym_COMMA,
    ACTIONS(327), 1,
      anon_sym_GT,
    STATE(87), 1,
      aux_sym_type_args_repeat1,
    STATE(98), 1,
      sym_comment,
  [2372] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(329), 1,
      anon_sym_COMMA,
    ACTIONS(332), 1,
      anon_sym_RBRACK,
    STATE(99), 2,
      sym_comment,
      aux_sym_source_repeat1,
  [2389] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(100), 1,
      sym_comment,
    ACTIONS(334), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_type_ident,
  [2404] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(101), 1,
      sym_comment,
    ACTIONS(336), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      sym_type_ident,
  [2419] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(109), 1,
      anon_sym_COMMA,
    ACTIONS(338), 1,
      anon_sym_RPAREN,
    STATE(97), 1,
      aux_sym_expr_list_repeat1,
    STATE(102), 1,
      sym_comment,
  [2438] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(325), 1,
      anon_sym_COMMA,
    ACTIONS(340), 1,
      anon_sym_GT,
    STATE(98), 1,
      aux_sym_type_args_repeat1,
    STATE(103), 1,
      sym_comment,
  [2457] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    ACTIONS(342), 1,
      anon_sym_RBRACK,
    STATE(80), 1,
      aux_sym_annotation_repeat1,
    STATE(104), 1,
      sym_comment,
  [2476] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(344), 1,
      anon_sym_RBRACK,
    STATE(99), 1,
      aux_sym_source_repeat1,
    STATE(105), 1,
      sym_comment,
  [2495] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(106), 1,
      sym_comment,
    ACTIONS(308), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2509] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(107), 1,
      sym_comment,
    ACTIONS(346), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2523] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(108), 1,
      sym_comment,
    ACTIONS(348), 2,
      sym_type_ident,
      sym_ident,
  [2537] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(109), 1,
      sym_comment,
    ACTIONS(299), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [2551] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(110), 1,
      sym_comment,
    ACTIONS(350), 2,
      sym_type_ident,
      sym_ident,
  [2565] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(111), 1,
      sym_comment,
    ACTIONS(332), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2579] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(352), 1,
      anon_sym_RPAREN,
    STATE(112), 1,
      sym_comment,
  [2592] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(354), 1,
      sym_ident,
    STATE(113), 1,
      sym_comment,
  [2605] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(356), 1,
      sym_ident,
    STATE(114), 1,
      sym_comment,
  [2618] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(358), 1,
      anon_sym_RBRACE,
    STATE(115), 1,
      sym_comment,
  [2631] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(360), 1,
      anon_sym_LBRACK,
    STATE(116), 1,
      sym_comment,
  [2644] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(362), 1,
      anon_sym_RBRACK,
    STATE(117), 1,
      sym_comment,
  [2657] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(364), 1,
      anon_sym__,
    STATE(118), 1,
      sym_comment,
  [2670] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(366), 1,
      sym_type_ident,
    STATE(119), 1,
      sym_comment,
  [2683] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(368), 1,
      anon_sym_LBRACK,
    STATE(120), 1,
      sym_comment,
  [2696] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(370), 1,
      anon_sym_LBRACE,
    STATE(121), 1,
      sym_comment,
  [2709] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(372), 1,
      sym_type_ident,
    STATE(122), 1,
      sym_comment,
  [2722] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(374), 1,
      anon_sym_LBRACE,
    STATE(123), 1,
      sym_comment,
  [2735] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(376), 1,
      anon_sym__,
    STATE(124), 1,
      sym_comment,
  [2748] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(378), 1,
      anon_sym_LT,
    STATE(125), 1,
      sym_comment,
  [2761] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(380), 1,
      sym_type_ident,
    STATE(126), 1,
      sym_comment,
  [2774] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(382), 1,
      sym_type_ident,
    STATE(127), 1,
      sym_comment,
  [2787] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(384), 1,
      anon_sym_LBRACK,
    STATE(128), 1,
      sym_comment,
  [2800] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(386), 1,
      sym_type_ident,
    STATE(129), 1,
      sym_comment,
  [2813] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(388), 1,
      sym_ident,
    STATE(130), 1,
      sym_comment,
  [2826] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(390), 1,
      sym_ident,
    STATE(131), 1,
      sym_comment,
  [2839] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(392), 1,
      sym_ident,
    STATE(132), 1,
      sym_comment,
  [2852] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(394), 1,
      anon_sym_RPAREN,
    STATE(133), 1,
      sym_comment,
  [2865] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(396), 1,
      sym_type_ident,
    STATE(134), 1,
      sym_comment,
  [2878] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(398), 1,
      sym_ident,
    STATE(135), 1,
      sym_comment,
  [2891] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(400), 1,
      sym_type_ident,
    STATE(136), 1,
      sym_comment,
  [2904] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(402), 1,
      anon_sym_GT,
    STATE(137), 1,
      sym_comment,
  [2917] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(404), 1,
      ts_builtin_sym_end,
    STATE(138), 1,
      sym_comment,
  [2930] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(406), 1,
      anon_sym_RBRACE,
    STATE(139), 1,
      sym_comment,
  [2943] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(408), 1,
      sym_type_ident,
    STATE(140), 1,
      sym_comment,
  [2956] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(410), 1,
      sym_ident,
    STATE(141), 1,
      sym_comment,
  [2969] = 1,
    ACTIONS(412), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 87,
  [SMALL_STATE(5)] = 120,
  [SMALL_STATE(6)] = 150,
  [SMALL_STATE(7)] = 186,
  [SMALL_STATE(8)] = 216,
  [SMALL_STATE(9)] = 248,
  [SMALL_STATE(10)] = 278,
  [SMALL_STATE(11)] = 308,
  [SMALL_STATE(12)] = 340,
  [SMALL_STATE(13)] = 370,
  [SMALL_STATE(14)] = 400,
  [SMALL_STATE(15)] = 434,
  [SMALL_STATE(16)] = 477,
  [SMALL_STATE(17)] = 518,
  [SMALL_STATE(18)] = 559,
  [SMALL_STATE(19)] = 602,
  [SMALL_STATE(20)] = 645,
  [SMALL_STATE(21)] = 679,
  [SMALL_STATE(22)] = 714,
  [SMALL_STATE(23)] = 749,
  [SMALL_STATE(24)] = 778,
  [SMALL_STATE(25)] = 813,
  [SMALL_STATE(26)] = 851,
  [SMALL_STATE(27)] = 879,
  [SMALL_STATE(28)] = 912,
  [SMALL_STATE(29)] = 941,
  [SMALL_STATE(30)] = 970,
  [SMALL_STATE(31)] = 999,
  [SMALL_STATE(32)] = 1028,
  [SMALL_STATE(33)] = 1057,
  [SMALL_STATE(34)] = 1086,
  [SMALL_STATE(35)] = 1119,
  [SMALL_STATE(36)] = 1151,
  [SMALL_STATE(37)] = 1180,
  [SMALL_STATE(38)] = 1209,
  [SMALL_STATE(39)] = 1236,
  [SMALL_STATE(40)] = 1262,
  [SMALL_STATE(41)] = 1284,
  [SMALL_STATE(42)] = 1304,
  [SMALL_STATE(43)] = 1330,
  [SMALL_STATE(44)] = 1352,
  [SMALL_STATE(45)] = 1374,
  [SMALL_STATE(46)] = 1396,
  [SMALL_STATE(47)] = 1418,
  [SMALL_STATE(48)] = 1440,
  [SMALL_STATE(49)] = 1466,
  [SMALL_STATE(50)] = 1488,
  [SMALL_STATE(51)] = 1507,
  [SMALL_STATE(52)] = 1526,
  [SMALL_STATE(53)] = 1543,
  [SMALL_STATE(54)] = 1560,
  [SMALL_STATE(55)] = 1581,
  [SMALL_STATE(56)] = 1602,
  [SMALL_STATE(57)] = 1621,
  [SMALL_STATE(58)] = 1640,
  [SMALL_STATE(59)] = 1657,
  [SMALL_STATE(60)] = 1676,
  [SMALL_STATE(61)] = 1693,
  [SMALL_STATE(62)] = 1712,
  [SMALL_STATE(63)] = 1729,
  [SMALL_STATE(64)] = 1748,
  [SMALL_STATE(65)] = 1765,
  [SMALL_STATE(66)] = 1784,
  [SMALL_STATE(67)] = 1803,
  [SMALL_STATE(68)] = 1822,
  [SMALL_STATE(69)] = 1839,
  [SMALL_STATE(70)] = 1856,
  [SMALL_STATE(71)] = 1873,
  [SMALL_STATE(72)] = 1892,
  [SMALL_STATE(73)] = 1911,
  [SMALL_STATE(74)] = 1930,
  [SMALL_STATE(75)] = 1949,
  [SMALL_STATE(76)] = 1969,
  [SMALL_STATE(77)] = 1989,
  [SMALL_STATE(78)] = 2007,
  [SMALL_STATE(79)] = 2025,
  [SMALL_STATE(80)] = 2043,
  [SMALL_STATE(81)] = 2062,
  [SMALL_STATE(82)] = 2079,
  [SMALL_STATE(83)] = 2094,
  [SMALL_STATE(84)] = 2113,
  [SMALL_STATE(85)] = 2128,
  [SMALL_STATE(86)] = 2147,
  [SMALL_STATE(87)] = 2166,
  [SMALL_STATE(88)] = 2183,
  [SMALL_STATE(89)] = 2198,
  [SMALL_STATE(90)] = 2217,
  [SMALL_STATE(91)] = 2232,
  [SMALL_STATE(92)] = 2249,
  [SMALL_STATE(93)] = 2264,
  [SMALL_STATE(94)] = 2283,
  [SMALL_STATE(95)] = 2302,
  [SMALL_STATE(96)] = 2321,
  [SMALL_STATE(97)] = 2336,
  [SMALL_STATE(98)] = 2353,
  [SMALL_STATE(99)] = 2372,
  [SMALL_STATE(100)] = 2389,
  [SMALL_STATE(101)] = 2404,
  [SMALL_STATE(102)] = 2419,
  [SMALL_STATE(103)] = 2438,
  [SMALL_STATE(104)] = 2457,
  [SMALL_STATE(105)] = 2476,
  [SMALL_STATE(106)] = 2495,
  [SMALL_STATE(107)] = 2509,
  [SMALL_STATE(108)] = 2523,
  [SMALL_STATE(109)] = 2537,
  [SMALL_STATE(110)] = 2551,
  [SMALL_STATE(111)] = 2565,
  [SMALL_STATE(112)] = 2579,
  [SMALL_STATE(113)] = 2592,
  [SMALL_STATE(114)] = 2605,
  [SMALL_STATE(115)] = 2618,
  [SMALL_STATE(116)] = 2631,
  [SMALL_STATE(117)] = 2644,
  [SMALL_STATE(118)] = 2657,
  [SMALL_STATE(119)] = 2670,
  [SMALL_STATE(120)] = 2683,
  [SMALL_STATE(121)] = 2696,
  [SMALL_STATE(122)] = 2709,
  [SMALL_STATE(123)] = 2722,
  [SMALL_STATE(124)] = 2735,
  [SMALL_STATE(125)] = 2748,
  [SMALL_STATE(126)] = 2761,
  [SMALL_STATE(127)] = 2774,
  [SMALL_STATE(128)] = 2787,
  [SMALL_STATE(129)] = 2800,
  [SMALL_STATE(130)] = 2813,
  [SMALL_STATE(131)] = 2826,
  [SMALL_STATE(132)] = 2839,
  [SMALL_STATE(133)] = 2852,
  [SMALL_STATE(134)] = 2865,
  [SMALL_STATE(135)] = 2878,
  [SMALL_STATE(136)] = 2891,
  [SMALL_STATE(137)] = 2904,
  [SMALL_STATE(138)] = 2917,
  [SMALL_STATE(139)] = 2930,
  [SMALL_STATE(140)] = 2943,
  [SMALL_STATE(141)] = 2956,
  [SMALL_STATE(142)] = 2969,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expr, 3),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_expr, 3),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expr, 3),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expr, 3),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda_expr, 3),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lambda_expr, 3),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expr, 4),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expr, 4),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expr, 2),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expr, 2),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expr, 6),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_expr, 6),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expr, 3),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 3),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 3),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expr, 5),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_expr, 5),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint, 2),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(30),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(116),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(132),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(25),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_def, 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_list, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_def, 2),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expr_list_repeat1, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(132),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(17),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_def, 3),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_def_repeat2, 2),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_def_repeat2, 2), SHIFT_REPEAT(38),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_def, 4),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 4),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_source, 4),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 5),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_source, 5),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 2),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 2),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 5),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 5),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_expr, 1),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_def_repeat1, 2), SHIFT_REPEAT(132),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_def_repeat1, 2),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wildcard, 1),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wildcard, 1),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_value, 1),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__field_value, 1),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_object, 5),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_block, 2),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nested_block, 2),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_args, 4),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 3),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_body, 1),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_type, 3),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_type, 3),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_args, 3),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 1),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_item, 1),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block_item, 1),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 4),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 4),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wildcard_object, 5),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_concrete_type, 4),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_object, 4),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 8),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_source, 8),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 9),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_source, 9),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 10),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_source, 10),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wildcard_object, 5),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 2),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [273] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_inline_object_repeat1, 2),
  [281] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inline_object_repeat1, 2), SHIFT_REPEAT(130),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__top_level, 1),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_args_repeat1, 2), SHIFT_REPEAT(122),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_args_repeat1, 2),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 5),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 6),
  [305] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_annotation_repeat1, 2), SHIFT_REPEAT(108),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_annotation_repeat1, 2),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_def_repeat1, 1),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 5),
  [322] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expr_list_repeat1, 2), SHIFT_REPEAT(29),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [329] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(141),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4),
  [338] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_list, 2),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [346] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_inline_object_repeat1, 3),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [370] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [404] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [412] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_ilk(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
