#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 78
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_EQ = 1,
  anon_sym_LT = 2,
  anon_sym_COMMA = 3,
  anon_sym_GT = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_QMARK = 7,
  anon_sym_STAR = 8,
  sym_string = 9,
  sym_number = 10,
  anon_sym_true = 11,
  anon_sym_false = 12,
  anon_sym_LBRACK = 13,
  anon_sym_RBRACK = 14,
  sym_type_ident = 15,
  sym_ident = 16,
  aux_sym_comment_token1 = 17,
  aux_sym_comment_token2 = 18,
  sym_source_file = 19,
  sym_definition = 20,
  sym_associations = 21,
  sym__body = 22,
  sym_block_body = 23,
  sym__item = 24,
  sym_field = 25,
  sym_nested_block = 26,
  sym__value = 27,
  sym_boolean = 28,
  sym_list = 29,
  sym__list_content = 30,
  sym__list_item = 31,
  sym_inline_object = 32,
  sym_object_field = 33,
  sym_type_refinement = 34,
  sym_comment = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_associations_repeat1 = 37,
  aux_sym_block_body_repeat1 = 38,
  aux_sym__list_content_repeat1 = 39,
  aux_sym_inline_object_repeat1 = 40,
  aux_sym_type_refinement_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_LT] = "<",
  [anon_sym_COMMA] = ",",
  [anon_sym_GT] = ">",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_QMARK] = "\?",
  [anon_sym_STAR] = "*",
  [sym_string] = "string",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_type_ident] = "type_ident",
  [sym_ident] = "ident",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [sym_source_file] = "source_file",
  [sym_definition] = "definition",
  [sym_associations] = "associations",
  [sym__body] = "_body",
  [sym_block_body] = "block_body",
  [sym__item] = "_item",
  [sym_field] = "field",
  [sym_nested_block] = "nested_block",
  [sym__value] = "_value",
  [sym_boolean] = "boolean",
  [sym_list] = "list",
  [sym__list_content] = "_list_content",
  [sym__list_item] = "_list_item",
  [sym_inline_object] = "inline_object",
  [sym_object_field] = "object_field",
  [sym_type_refinement] = "type_refinement",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_associations_repeat1] = "associations_repeat1",
  [aux_sym_block_body_repeat1] = "block_body_repeat1",
  [aux_sym__list_content_repeat1] = "_list_content_repeat1",
  [aux_sym_inline_object_repeat1] = "inline_object_repeat1",
  [aux_sym_type_refinement_repeat1] = "type_refinement_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_type_ident] = sym_type_ident,
  [sym_ident] = sym_ident,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [sym_source_file] = sym_source_file,
  [sym_definition] = sym_definition,
  [sym_associations] = sym_associations,
  [sym__body] = sym__body,
  [sym_block_body] = sym_block_body,
  [sym__item] = sym__item,
  [sym_field] = sym_field,
  [sym_nested_block] = sym_nested_block,
  [sym__value] = sym__value,
  [sym_boolean] = sym_boolean,
  [sym_list] = sym_list,
  [sym__list_content] = sym__list_content,
  [sym__list_item] = sym__list_item,
  [sym_inline_object] = sym_inline_object,
  [sym_object_field] = sym_object_field,
  [sym_type_refinement] = sym_type_refinement,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_associations_repeat1] = aux_sym_associations_repeat1,
  [aux_sym_block_body_repeat1] = aux_sym_block_body_repeat1,
  [aux_sym__list_content_repeat1] = aux_sym__list_content_repeat1,
  [aux_sym_inline_object_repeat1] = aux_sym_inline_object_repeat1,
  [aux_sym_type_refinement_repeat1] = aux_sym_type_refinement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_type_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_associations] = {
    .visible = true,
    .named = true,
  },
  [sym__body] = {
    .visible = false,
    .named = true,
  },
  [sym_block_body] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_nested_block] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__list_content] = {
    .visible = false,
    .named = true,
  },
  [sym__list_item] = {
    .visible = false,
    .named = true,
  },
  [sym_inline_object] = {
    .visible = true,
    .named = true,
  },
  [sym_object_field] = {
    .visible = true,
    .named = true,
  },
  [sym_type_refinement] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_associations_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__list_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_inline_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_refinement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '<') ADVANCE(11);
      if (lookahead == '=') ADVANCE(10);
      if (lookahead == '>') ADVANCE(13);
      if (lookahead == '?') ADVANCE(16);
      if (lookahead == '[') ADVANCE(23);
      if (lookahead == ']') ADVANCE(24);
      if (lookahead == 'f') ADVANCE(26);
      if (lookahead == 't') ADVANCE(30);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(34);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '<') ADVANCE(11);
      if (lookahead == '?') ADVANCE(16);
      if (lookahead == ']') ADVANCE(24);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_type_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'a') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 's') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'u') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 8},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 8},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 8},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 8},
  [52] = {.lex_state = 8},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 8},
  [58] = {.lex_state = 8},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 8},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 8},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 8},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 8},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 8},
  [76] = {.lex_state = 0},
  [77] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_type_ident] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(3),
    [aux_sym_comment_token2] = ACTIONS(5),
  },
  [1] = {
    [sym_source_file] = STATE(70),
    [sym_definition] = STATE(61),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_ident] = ACTIONS(5),
    [aux_sym_comment_token1] = ACTIONS(3),
    [aux_sym_comment_token2] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_QMARK,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_ident,
    STATE(2), 1,
      sym_comment,
    STATE(42), 1,
      sym__value,
    STATE(71), 1,
      sym_associations,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      sym_string,
      sym_number,
      sym_type_ident,
    STATE(68), 3,
      sym_boolean,
      sym_list,
      sym_type_refinement,
  [48] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_ident,
    ACTIONS(25), 1,
      anon_sym_STAR,
    STATE(3), 1,
      sym_comment,
    STATE(46), 1,
      sym__value,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      sym_string,
      sym_number,
      sym_type_ident,
    STATE(68), 3,
      sym_boolean,
      sym_list,
      sym_type_refinement,
  [84] = 9,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_ident,
    STATE(4), 1,
      sym_comment,
    STATE(46), 1,
      sym__value,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      sym_string,
      sym_number,
      sym_type_ident,
    STATE(68), 3,
      sym_boolean,
      sym_list,
      sym_type_refinement,
  [117] = 9,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_ident,
    STATE(5), 1,
      sym_comment,
    STATE(52), 1,
      sym__value,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      sym_string,
      sym_number,
      sym_type_ident,
    STATE(68), 3,
      sym_boolean,
      sym_list,
      sym_type_refinement,
  [150] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_string,
    STATE(6), 1,
      sym_comment,
    STATE(11), 1,
      sym_associations,
    STATE(45), 1,
      sym__body,
    STATE(50), 1,
      sym_block_body,
    ACTIONS(27), 2,
      ts_builtin_sym_end,
      sym_ident,
  [182] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
    ACTIONS(37), 1,
      sym_type_ident,
    ACTIONS(39), 1,
      sym_ident,
    STATE(7), 1,
      sym_comment,
    STATE(25), 1,
      sym__list_item,
    STATE(76), 1,
      sym__list_content,
    STATE(48), 2,
      sym_inline_object,
      sym_type_refinement,
  [214] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(43), 1,
      sym_ident,
    STATE(8), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_block_body_repeat1,
    STATE(51), 1,
      sym__item,
    STATE(54), 2,
      sym_field,
      sym_nested_block,
  [240] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(43), 1,
      sym_ident,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      sym_comment,
    STATE(16), 1,
      aux_sym_block_body_repeat1,
    STATE(51), 1,
      sym__item,
    STATE(54), 2,
      sym_field,
      sym_nested_block,
  [266] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(43), 1,
      sym_ident,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(10), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym_block_body_repeat1,
    STATE(51), 1,
      sym__item,
    STATE(54), 2,
      sym_field,
      sym_nested_block,
  [292] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_string,
    STATE(11), 1,
      sym_comment,
    STATE(50), 1,
      sym_block_body,
    STATE(58), 1,
      sym__body,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      sym_ident,
  [318] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(43), 1,
      sym_ident,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      sym_comment,
    STATE(14), 1,
      aux_sym_block_body_repeat1,
    STATE(51), 1,
      sym__item,
    STATE(54), 2,
      sym_field,
      sym_nested_block,
  [344] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      sym_type_ident,
    ACTIONS(39), 1,
      sym_ident,
    STATE(13), 1,
      sym_comment,
    STATE(66), 1,
      sym__list_item,
    STATE(48), 2,
      sym_inline_object,
      sym_type_refinement,
  [370] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    ACTIONS(53), 1,
      sym_ident,
    STATE(51), 1,
      sym__item,
    STATE(14), 2,
      sym_comment,
      aux_sym_block_body_repeat1,
    STATE(54), 2,
      sym_field,
      sym_nested_block,
  [394] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(43), 1,
      sym_ident,
    ACTIONS(56), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      aux_sym_block_body_repeat1,
    STATE(15), 1,
      sym_comment,
    STATE(51), 1,
      sym__item,
    STATE(54), 2,
      sym_field,
      sym_nested_block,
  [420] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(43), 1,
      sym_ident,
    ACTIONS(58), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      aux_sym_block_body_repeat1,
    STATE(16), 1,
      sym_comment,
    STATE(51), 1,
      sym__item,
    STATE(54), 2,
      sym_field,
      sym_nested_block,
  [446] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 1,
      sym_ident,
    STATE(61), 1,
      sym_definition,
    STATE(17), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
  [466] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(18), 1,
      sym_comment,
    ACTIONS(65), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      sym_ident,
  [482] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(19), 1,
      sym_comment,
    ACTIONS(67), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_string,
      sym_ident,
  [498] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      aux_sym_source_file_repeat1,
    STATE(20), 1,
      sym_comment,
    STATE(61), 1,
      sym_definition,
    ACTIONS(5), 2,
      sym_ident,
      aux_sym_comment_token2,
  [518] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(21), 1,
      sym_comment,
    ACTIONS(71), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      sym_ident,
  [534] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(75), 1,
      anon_sym_QMARK,
    ACTIONS(77), 1,
      anon_sym_STAR,
    STATE(22), 1,
      sym_comment,
    ACTIONS(73), 2,
      anon_sym_RBRACE,
      sym_ident,
  [554] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(23), 1,
      sym_comment,
    ACTIONS(79), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_string,
      sym_ident,
  [570] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(84), 1,
      anon_sym_GT,
    STATE(24), 2,
      sym_comment,
      aux_sym_associations_repeat1,
  [587] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    ACTIONS(88), 1,
      anon_sym_RBRACK,
    STATE(25), 1,
      sym_comment,
    STATE(34), 1,
      aux_sym__list_content_repeat1,
  [606] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(92), 1,
      anon_sym_STAR,
    STATE(26), 1,
      sym_comment,
    ACTIONS(90), 2,
      anon_sym_RBRACE,
      sym_ident,
  [623] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(94), 1,
      anon_sym_COMMA,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    STATE(27), 2,
      sym_comment,
      aux_sym_inline_object_repeat1,
  [640] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    ACTIONS(99), 1,
      sym_ident,
    STATE(28), 2,
      sym_comment,
      aux_sym_type_refinement_repeat1,
  [657] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    ACTIONS(104), 1,
      anon_sym_GT,
    STATE(24), 1,
      aux_sym_associations_repeat1,
    STATE(29), 1,
      sym_comment,
  [676] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    ACTIONS(109), 1,
      anon_sym_RBRACK,
    STATE(30), 2,
      sym_comment,
      aux_sym__list_content_repeat1,
  [693] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(111), 1,
      anon_sym_COMMA,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      aux_sym_inline_object_repeat1,
    STATE(31), 1,
      sym_comment,
  [712] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym_comment,
    ACTIONS(117), 2,
      anon_sym_RBRACE,
      sym_ident,
  [729] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    ACTIONS(121), 1,
      sym_ident,
    STATE(28), 1,
      aux_sym_type_refinement_repeat1,
    STATE(33), 1,
      sym_comment,
  [748] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    ACTIONS(123), 1,
      anon_sym_RBRACK,
    STATE(30), 1,
      aux_sym__list_content_repeat1,
    STATE(34), 1,
      sym_comment,
  [767] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(35), 1,
      sym_comment,
    ACTIONS(125), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_ident,
  [782] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(111), 1,
      anon_sym_COMMA,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      aux_sym_inline_object_repeat1,
    STATE(36), 1,
      sym_comment,
  [801] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    STATE(37), 1,
      sym_comment,
    ACTIONS(129), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [818] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(121), 1,
      sym_ident,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      aux_sym_type_refinement_repeat1,
    STATE(38), 1,
      sym_comment,
  [837] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(39), 1,
      sym_comment,
    ACTIONS(133), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_ident,
  [852] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    ACTIONS(135), 1,
      anon_sym_GT,
    STATE(29), 1,
      aux_sym_associations_repeat1,
    STATE(40), 1,
      sym_comment,
  [871] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(41), 1,
      sym_comment,
    ACTIONS(137), 2,
      anon_sym_RBRACE,
      sym_ident,
  [885] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(42), 1,
      sym_comment,
    ACTIONS(139), 2,
      anon_sym_RBRACE,
      sym_ident,
  [899] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(43), 1,
      sym_comment,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      sym_ident,
  [913] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(44), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_RBRACE,
      sym_ident,
  [927] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(45), 1,
      sym_comment,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      sym_ident,
  [941] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(46), 1,
      sym_comment,
    ACTIONS(145), 2,
      anon_sym_RBRACE,
      sym_ident,
  [955] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(147), 1,
      sym_ident,
    STATE(36), 1,
      sym_object_field,
    STATE(47), 1,
      sym_comment,
  [971] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(48), 1,
      sym_comment,
    ACTIONS(129), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [985] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(49), 1,
      sym_comment,
    ACTIONS(149), 2,
      anon_sym_RBRACE,
      sym_ident,
  [999] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(50), 1,
      sym_comment,
    ACTIONS(151), 2,
      ts_builtin_sym_end,
      sym_ident,
  [1013] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(51), 1,
      sym_comment,
    ACTIONS(153), 2,
      anon_sym_RBRACE,
      sym_ident,
  [1027] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(52), 1,
      sym_comment,
    ACTIONS(155), 2,
      anon_sym_RBRACE,
      sym_ident,
  [1041] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    STATE(53), 1,
      sym_comment,
    STATE(62), 1,
      sym_list,
  [1057] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(54), 1,
      sym_comment,
    ACTIONS(157), 2,
      anon_sym_RBRACE,
      sym_ident,
  [1071] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(55), 1,
      sym_comment,
    ACTIONS(84), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1085] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(56), 1,
      sym_comment,
    ACTIONS(90), 2,
      anon_sym_RBRACE,
      sym_ident,
  [1099] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(57), 1,
      sym_comment,
    ACTIONS(159), 2,
      ts_builtin_sym_end,
      sym_ident,
  [1113] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(58), 1,
      sym_comment,
    ACTIONS(161), 2,
      ts_builtin_sym_end,
      sym_ident,
  [1127] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(59), 1,
      sym_comment,
    ACTIONS(163), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1141] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(60), 1,
      sym_comment,
    ACTIONS(97), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1155] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(61), 1,
      sym_comment,
    ACTIONS(165), 2,
      ts_builtin_sym_end,
      sym_ident,
  [1169] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(62), 1,
      sym_comment,
    ACTIONS(167), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1183] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(147), 1,
      sym_ident,
    STATE(60), 1,
      sym_object_field,
    STATE(63), 1,
      sym_comment,
  [1199] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(64), 1,
      sym_comment,
    ACTIONS(169), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1213] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(65), 1,
      sym_comment,
    ACTIONS(171), 2,
      anon_sym_RBRACE,
      sym_ident,
  [1227] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(66), 1,
      sym_comment,
    ACTIONS(109), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1241] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(67), 1,
      sym_comment,
    ACTIONS(173), 2,
      anon_sym_RBRACE,
      sym_ident,
  [1255] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(68), 1,
      sym_comment,
    ACTIONS(117), 2,
      anon_sym_RBRACE,
      sym_ident,
  [1269] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(175), 1,
      anon_sym_EQ,
    STATE(69), 1,
      sym_comment,
  [1282] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
    STATE(70), 1,
      sym_comment,
  [1295] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(179), 1,
      anon_sym_LBRACE,
    STATE(71), 1,
      sym_comment,
  [1308] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(181), 1,
      sym_type_ident,
    STATE(72), 1,
      sym_comment,
  [1321] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(183), 1,
      sym_ident,
    STATE(73), 1,
      sym_comment,
  [1334] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(185), 1,
      sym_type_ident,
    STATE(74), 1,
      sym_comment,
  [1347] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(187), 1,
      sym_ident,
    STATE(75), 1,
      sym_comment,
  [1360] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(189), 1,
      anon_sym_RBRACK,
    STATE(76), 1,
      sym_comment,
  [1373] = 1,
    ACTIONS(191), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 117,
  [SMALL_STATE(6)] = 150,
  [SMALL_STATE(7)] = 182,
  [SMALL_STATE(8)] = 214,
  [SMALL_STATE(9)] = 240,
  [SMALL_STATE(10)] = 266,
  [SMALL_STATE(11)] = 292,
  [SMALL_STATE(12)] = 318,
  [SMALL_STATE(13)] = 344,
  [SMALL_STATE(14)] = 370,
  [SMALL_STATE(15)] = 394,
  [SMALL_STATE(16)] = 420,
  [SMALL_STATE(17)] = 446,
  [SMALL_STATE(18)] = 466,
  [SMALL_STATE(19)] = 482,
  [SMALL_STATE(20)] = 498,
  [SMALL_STATE(21)] = 518,
  [SMALL_STATE(22)] = 534,
  [SMALL_STATE(23)] = 554,
  [SMALL_STATE(24)] = 570,
  [SMALL_STATE(25)] = 587,
  [SMALL_STATE(26)] = 606,
  [SMALL_STATE(27)] = 623,
  [SMALL_STATE(28)] = 640,
  [SMALL_STATE(29)] = 657,
  [SMALL_STATE(30)] = 676,
  [SMALL_STATE(31)] = 693,
  [SMALL_STATE(32)] = 712,
  [SMALL_STATE(33)] = 729,
  [SMALL_STATE(34)] = 748,
  [SMALL_STATE(35)] = 767,
  [SMALL_STATE(36)] = 782,
  [SMALL_STATE(37)] = 801,
  [SMALL_STATE(38)] = 818,
  [SMALL_STATE(39)] = 837,
  [SMALL_STATE(40)] = 852,
  [SMALL_STATE(41)] = 871,
  [SMALL_STATE(42)] = 885,
  [SMALL_STATE(43)] = 899,
  [SMALL_STATE(44)] = 913,
  [SMALL_STATE(45)] = 927,
  [SMALL_STATE(46)] = 941,
  [SMALL_STATE(47)] = 955,
  [SMALL_STATE(48)] = 971,
  [SMALL_STATE(49)] = 985,
  [SMALL_STATE(50)] = 999,
  [SMALL_STATE(51)] = 1013,
  [SMALL_STATE(52)] = 1027,
  [SMALL_STATE(53)] = 1041,
  [SMALL_STATE(54)] = 1057,
  [SMALL_STATE(55)] = 1071,
  [SMALL_STATE(56)] = 1085,
  [SMALL_STATE(57)] = 1099,
  [SMALL_STATE(58)] = 1113,
  [SMALL_STATE(59)] = 1127,
  [SMALL_STATE(60)] = 1141,
  [SMALL_STATE(61)] = 1155,
  [SMALL_STATE(62)] = 1169,
  [SMALL_STATE(63)] = 1183,
  [SMALL_STATE(64)] = 1199,
  [SMALL_STATE(65)] = 1213,
  [SMALL_STATE(66)] = 1227,
  [SMALL_STATE(67)] = 1241,
  [SMALL_STATE(68)] = 1255,
  [SMALL_STATE(69)] = 1269,
  [SMALL_STATE(70)] = 1282,
  [SMALL_STATE(71)] = 1295,
  [SMALL_STATE(72)] = 1308,
  [SMALL_STATE(73)] = 1321,
  [SMALL_STATE(74)] = 1334,
  [SMALL_STATE(75)] = 1347,
  [SMALL_STATE(76)] = 1360,
  [SMALL_STATE(77)] = 1373,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 3),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 4),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_body_repeat1, 2),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_body_repeat1, 2), SHIFT_REPEAT(2),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(69),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_refinement, 4),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_associations, 4),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_refinement, 3),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_refinement_repeat1, 2),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_associations, 3),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_associations_repeat1, 2), SHIFT_REPEAT(73),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_associations_repeat1, 2),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list_content, 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_refinement_repeat1, 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inline_object_repeat1, 2), SHIFT_REPEAT(63),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_inline_object_repeat1, 2),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_refinement_repeat1, 2), SHIFT_REPEAT(72),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__list_content_repeat1, 2), SHIFT_REPEAT(13),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__list_content_repeat1, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list_content, 2),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list_item, 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_block, 4),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_body, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_block, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_refinement_repeat1, 4),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__body, 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_body_repeat1, 1),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 4),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 1),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_body, 3),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 5),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_object, 4),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_field, 2),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_object, 3),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_block, 5),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [177] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_kli(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
